#:kivy 2.0.0

<HomeScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: '16dp'
        spacing: '16dp'
        
        # Espacio superior flexible
        Widget:
            size_hint_y: 0.1

        TitleLabel:
            text: 'Open Canoe Fantasy'
            size_hint_y: None
            height: '64dp'
            halign: 'center'
            
        

        Image:
            source: 'assets/images/app_icon.png'
            size_hint: (0.8, None)
            height: '150dp'  
            pos_hint: {'center_x': 0.5}
            allow_stretch: False
            keep_ratio: True
            
            
        BoxLayout:
            orientation: 'vertical'
            padding: '16dp'
            spacing: '16dp'
        
            TitleLabel:
                text: 'Iniciar Sesión'

            TextInput:
                id: email
                hint_text: 'Correo electrónico'
            
            TextInput:
                id: password
                hint_text: 'Contraseña'
                password: True
            
            Label:
                text: root.error_message
                color: error_color  # Usando el color de error definido en styles.kv
                size_hint_y: None
                height: self.texture_size[1]
                opacity: 1 if root.error_message else 0
            

            Button:
                text: 'Iniciar Sesión'
                size_hint_x: 0.8
                pos_hint: {'center_x': 0.5}
                on_release: root.login()

            Widget:
                size_hint_y: 0.5

            SecondaryButton:
                text: 'Registrarse'
                size_hint_x: 0.8
                pos_hint: {'center_x': 0.5}
                on_release: root.register()
        
        # Espacio inferior flexible
        Widget:
            size_hint_y: 0.1